[package]
name = "directive-malformed-trailing-text"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata.skeletons]

[package.metadata.skeletons.options.workflows]
type = "set"
default = ["lint"]

[[package.metadata.skeletons.options.workflows.values]]
value = "lint"
partial = "lint.yml"
