// @generated by ritual — do not edit.
//
// Every task named in [package.metadata.ritual] tasks in this crate's Cargo.toml
// is handed to the framework below. Change that list, then run this command
// line's `regenerate` task.
//
// If this file stopped compiling because a task's dependency was removed before
// its entry was dropped from that list: put the dependency back, drop the entry,
// run `regenerate`, then remove the dependency.

//! The composed `skeletons-ritual` command line.

// rustfmt is skipped here on purpose: this file has to be reproducible byte for
// byte, and that is only true while one thing decides its formatting. Predicting
// where rustfmt breaks a line is a moving target, not a contract.
#[rustfmt::skip]
fn main() -> std::process::ExitCode {
    rituals::run(
        rituals::identity!(),
        [
            ("ritual", ritual::task()),
            ("skeletons", skeletons::task()),
        ],
    )
}
